name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  splitAccounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Convert & split accounts
        run: |
          npm i
          npm run convertEmails
          npm run splitAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Splited accounts"; git push origin "$GITHUB_SHA-branch"; fi

  job0-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 0
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=0; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №0"; git push origin "$GITHUB_SHA-branch"; fi

  job1-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 1
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=1; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №1"; git push origin "$GITHUB_SHA-branch"; fi

  job2-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 2
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=2; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №2"; git push origin "$GITHUB_SHA-branch"; fi

  job3-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 3
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=3; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №3"; git push origin "$GITHUB_SHA-branch"; fi

  job4-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 4
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=4; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №4"; git push origin "$GITHUB_SHA-branch"; fi

  job5-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 5
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=5; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №5"; git push origin "$GITHUB_SHA-branch"; fi

  job6-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 6
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=6; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №6"; git push origin "$GITHUB_SHA-branch"; fi

  job7-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 7
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=7; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №7"; git push origin "$GITHUB_SHA-branch"; fi

  job8-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 8
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=8; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №8"; git push origin "$GITHUB_SHA-branch"; fi

  job9-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 9
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=9; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №9"; git push origin "$GITHUB_SHA-branch"; fi

  job10-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 10
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=10; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №10"; git push origin "$GITHUB_SHA-branch"; fi

  job11-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 11
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=11; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №11"; git push origin "$GITHUB_SHA-branch"; fi

  job12-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 12
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=12; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №12"; git push origin "$GITHUB_SHA-branch"; fi

  job13-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 13
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=13; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №13"; git push origin "$GITHUB_SHA-branch"; fi

  job14-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 14
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=14; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Processed accounts №14"; git push origin "$GITHUB_SHA-branch"; fi

  mergeAccounts:
    runs-on: ubuntu-latest
    needs:
      [
        job0-processAccounts,
        job1-processAccounts,
        job2-processAccounts,
        job3-processAccounts,
        job4-processAccounts,
        job5-processAccounts,
        job6-processAccounts,
        job7-processAccounts,
        job8-processAccounts,
        job9-processAccounts,
        job10-processAccounts,
        job11-processAccounts,
        job12-processAccounts,
        job13-processAccounts,
        job14-processAccounts,
      ]
    steps:
      - uses: actions/checkout@master

      - name: Merge Files & Cleanup
        run: |
          npm i
          npm run mergeAccounts
          npm run tempCleanup

      - name: Commit & Merge branches
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git pull origin; git stash; git checkout -b "$GITHUB_SHA-branch"; git stash pop; git add -A; git commit -m "Cleanup"; git push origin "$GITHUB_SHA-branch"; git checkout master; git merge "$GITHUB_SHA-branch"; git push origin master fi
