name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint & prettier
        run: |
          npm i
          npm run lint-check
          npm run prettier-check

  turnOffFirewalls:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Convert emails
        run: npm run convertEmails

      - name: Turn off firewall
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm run turnOffFirewall

      - name: Commit
        if: ${{ always() }}
        run: if [ -z "$(git diff --exit-code)" ]; then echo "Nothing to commit"; exit 0; else git config --global user.name "github-actions[bot]"; git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"; git add -A; git commit -m "Auto-push with converted emails"; git push origin master; fi
