name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  splitAccounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Convert & split accounts
        run: |
          npm i
          npm run convertEmails
          npm run splitAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitSplit.sh

  job0-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 0
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=0; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job1-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 1
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=1; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job2-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 2
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=2; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job3-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 3
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=3; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job4-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 4
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=4; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job5-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 5
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=5; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job6-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 6
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=6; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job7-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 7
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=7; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job8-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 8
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=8; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job9-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 9
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=9; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job10-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 10
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=10; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job11-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 11
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=11; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job12-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 12
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=12; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job13-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 13
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=13; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  job14-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 14
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: export DATABASE_PART=14; npm run processAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitProcess.sh

  mergeAccounts:
    runs-on: ubuntu-latest
    needs:
      [
        job0-processAccounts,
        job1-processAccounts,
        job2-processAccounts,
        job3-processAccounts,
        job4-processAccounts,
        job5-processAccounts,
        job6-processAccounts,
        job7-processAccounts,
        job8-processAccounts,
        job9-processAccounts,
        job10-processAccounts,
        job11-processAccounts,
        job12-processAccounts,
        job13-processAccounts,
        job14-processAccounts,
      ]
    steps:
      - uses: actions/checkout@master

      - name: Merge Files & Cleanup
        run: |
          npm i
          npm run mergeAccounts
          npm run tempCleanup

      - name: Commit & Merge branches
        if: ${{ always() }}
        run: sh ./src/sh/commitMerge.sh 
