name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint & prettier
      - uses: actions/checkout@v2
        run: |
          npm i
          npm run lint-check
          npm run prettier-check

  convertEmails:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Convert emails
      - uses: actions/checkout@v2
        run: |
          npm i
          npm run convertEmails
          git commit -m "Auto-push with converted emails"
          git push origin master

  turnOffFirewalls:
    runs-on: ubuntu-latest
    needs: convertEmails
    steps:
      - name: install puppeteer container
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args: pnpm i
      - name: Test
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args:
            [
              pnpm run turnOffFirewall,
              git commit -m "Auto-push with updated database",
              git push origin master,
            ]
