name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint & prettier
        run: |
          npm i
          npm run lint-check
          npm run prettier-check

  convertEmails:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Convert emails
        run: |
          npm i
          npm run convertEmails
          if [ -z \"$(git status --porcelain)\" ]; then exit 0; else git config --global user.email "kovylin1910@gmail.com"; git config --global user.name "KovylinDenis"; git commit -m "Auto-push with converted emails"; git push origin master; fi

  turnOffFirewalls:
    runs-on: ubuntu-latest
    needs: convertEmails
    steps:
      - name: install puppeteer container
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args: pnpm i
      - name: turn off firewalls
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args: pnpm run turnOffFirewall
      - name: Convert emails
        run: |
          npm run exitIfNoChanges
          if [ -z \"$(git status --porcelain)\" ]; then exit 0; else git config --global user.email "kovylin1910@gmail.com"; git config --global user.name "KovylinDenis"; git commit -m "Auto-push with converted emails"; git push origin master; fi
