name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  splitAccounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Convert & split accounts
        run: |
          npm i
          npm run convertEmails
          npm run splitAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitSplit.sh
