name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  splitAccounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Convert & split accounts
        run: |
          npm i
          npm run convertEmails
          npm run splitAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitSplit.sh

  job0-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 0
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 0
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-0
          path: src/database/temp/0.json

  job1-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 1
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 1
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-1
          path: src/database/temp/1.json

  job2-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 2
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 2
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-2
          path: src/database/temp/2.json

  job3-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 3
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 3
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-3
          path: src/database/temp/3.json

  job4-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 4
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 4
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-4
          path: src/database/temp/4.json

  job5-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 5
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 5
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-5
          path: src/database/temp/5.json

  job6-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 6
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 6
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-6
          path: src/database/temp/6.json

  job7-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 7
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 7
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-7
          path: src/database/temp/7.json

  job8-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 8
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 8
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-8
          path: src/database/temp/8.json

  job9-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 9
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 9
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-9
          path: src/database/temp/9.json

  job10-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 10
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 10
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-10
          path: src/database/temp/10.json

  job11-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 11
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 11
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-11
          path: src/database/temp/11.json

  job12-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 12
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 12
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-12
          path: src/database/temp/12.json

  job13-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 13
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 13
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-13
          path: src/database/temp/13.json

  job14-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 14
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 14
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Create partial artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact-processed-14
          path: src/database/temp/14.json

  mergeAccounts:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      [
        job0-processAccounts,
        job1-processAccounts,
        job2-processAccounts,
        job3-processAccounts,
        job4-processAccounts,
        job5-processAccounts,
        job6-processAccounts,
        job7-processAccounts,
        job8-processAccounts,
        job9-processAccounts,
        job10-processAccounts,
        job11-processAccounts,
        job12-processAccounts,
        job13-processAccounts,
        job14-processAccounts,
      ]
    steps:
      - uses: actions/checkout@master

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: src/database/temp/artifacts

      - name: Merge Files & Cleanup
        run: |
          npm i
          sh ./src/sh/setupMerge.sh

      - name: Commit & Merge branches
        if: ${{ always() }}
        run: sh ./src/sh/commitMerge.sh
