name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint & prettier
        run: |
          npm i
          npm run lint-check
          npm run prettier-check

  turnOffFirewalls:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Turn off Firewall & Turn on IMAP for users
        run: |
          npm i
          npm run convertEmails
          npm run turnOffFirewall
