name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  splitAccounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Convert & split accounts
        run: |
          npm i
          npm run convertEmails
          npm run splitAccounts

      - name: Commit
        if: ${{ always() }}
        run: sh ./src/sh/commitSplit.sh

  job0-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 0
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 0
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 0
        run: npm run loopCommit

  job1-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 1
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 1
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 1
        run: npm run loopCommit

  job2-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 2
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 2
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 2
        run: npm run loopCommit

  job3-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 3
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 3
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 3
        run: npm run loopCommit

  job4-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 4
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 4
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 4
        run: npm run loopCommit

  job5-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 5
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 5
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 5
        run: npm run loopCommit

  job6-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 6
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 6
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 6
        run: npm run loopCommit

  job7-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 7
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 7
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 7
        run: npm run loopCommit

  job8-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 8
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 8
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 8
        run: npm run loopCommit

  job9-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 9
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 9
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 9
        run: npm run loopCommit

  job10-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 10
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 10
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 10
        run: npm run loopCommit

  job11-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 11
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 11
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 11
        run: npm run loopCommit

  job12-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 12
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 12
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 12
        run: npm run loopCommit

  job13-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 13
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 13
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 13
        run: npm run loopCommit

  job14-processAccounts:
    runs-on: ubuntu-latest
    needs: splitAccounts
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Process Accounts part 14
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          DATABASE_PART: 14
        with:
          args: sh ./src/sh/setupProcess.sh

      - name: Commit
        if: ${{ always() }}
        env:
          DATABASE_PART: 14
        run: npm run loopCommit

  mergeAccounts:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      [
        job0-processAccounts,
        job1-processAccounts,
        job2-processAccounts,
        job3-processAccounts,
        job4-processAccounts,
        job5-processAccounts,
        job6-processAccounts,
        job7-processAccounts,
        job8-processAccounts,
        job9-processAccounts,
        job10-processAccounts,
        job11-processAccounts,
        job12-processAccounts,
        job13-processAccounts,
        job14-processAccounts,
      ]
    steps:
      - uses: actions/checkout@master

      - name: Merge Files & Cleanup
        run: |
          npm i
          sh ./src/sh/setupMerge.sh

      - name: Commit & Merge branches
        if: ${{ always() }}
        run: sh ./src/sh/commitMerge.sh
